# Lab book

The purpose of this file is to be a playground and place for
documentation at the same time. This is were you try different things,
and write about what you have tried and why, a place to write "dirty"
code so that the rest of your project can be kept clean. See this
mostly as a reference for your future self and use it in a way that
makes sense to you.

inga barn med (15 under)
delay är OFI. vilka patienter?
traumaregister kopplat till swetrau, inte samma dock. swetrau, NISS 15, NKS ESS 9 b.l.a.
kvalitetsregister är det konferenser sammanställer. auditfilters faller där, kallar till konferens om OFI är positivt
create OFI, skapar binärt ja eller nej.
typ. delta time. ph prehospital. ed emergency department
kolum är tiden till första hjälpande insats. kolum är i minuter, kom till hjälp.
olika faktorer som höjer tid.
DT treatment finns ej på 43% OFI, 74% av ej OFI.
dt_ed_emerg_prod är min

mycket data finns på patientfaktorer o mortalitet, men ej fördröjning

konferenser ovalninga globalt, resurskrävande. bara KS i sverige. nästan alla sjukhus går igenom dödsfall.
Finns på KI 2010-2012. hjärtstopp ung man, vet ej hur man skulle göra. intresekonflikt mellan medicin o kirurg.
gunilla wilke? anestesisköterska styrde upp mha två läkare kvalitetsförbättringsarbete. 2013 började? 
gick först igenom dödsfall, sen utanför mortalitet. försökte inkorporera audit filters, mellan 2013-2017 audit filter för brett. valde patienter på måfå.
gjorde om filter till de vi har nu, fick in en till sjuksyrra. liselott applicerar alla filter, typ 9 olika. om ja, går igenom pat med gunilla.
på konferens alla som sysslar med trauma

plan B, vi har all data så det ska gå


  
tog bort
csl: bmcemerg.csl