---
title: "Trauma treatment delay"
author: "Anton Wasielewski"
subtitle: A retrospective cohort study on the factors affecting the delays in trauma
  care
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
bibliography: bibliography.bib
---

# Introduction

**Definition**

Within modern hospital care, trauma care stands as an important part in healthcare and is crucial to lowering mortality and morbidity in injured patients<!-- Not only hospital trauma care, you may want to mention the entire system already here-->. The definition of trauma is "a set of psychological and physiological responses to pain, injury, serious illness, medical procedures and frightening treatment experiences" [@International_Society_for_Traumatic_Stress_Studies_2020]. As the definition suggests, it encompasses a broad spectrum of different conditions, both physical and psychological<!-- I don't think you need this definition here, it doesn't really fit-->. The one we will be focusing on in this paper is physical trauma, the clinical entity composed of physical injury and the body's associated response, hereby referred to as trauma.

**Trauma statistics**

It is often divided into two subgroups<!-- By "it", do you mean trauma? Suggest you just write so-->, blunt force trauma and penetrating trauma. Blunt force trauma is when an object or force strikes the body, often causing bruising, broken bones or deep cuts. Examples of this could be car crashes, falls or direct blows to the body. Penetrating<!-- More common to refer to it as penetrating, rather than penetrative--> trauma is when an object pierces the skin or body and creates an open wound. Examples of this<!-- By "this", do you mean penetrating trauma mechanisms?--> are gunshot wounds and stab wounds [@National_Institute_of_General_Medical_Sciences_2020]. Differences exist between the two groups, as blunt trauma patients tend to score higher on ISS scale<!-- You haven't mentioned ISS before here. Do you mean that blunt trauma patients are more severely injured?--> on arrival and as such require more resources and be hospitalized for a longer period because of their more severe injuries.

Trauma is and has long been a major cause of death around the world today, taking the lives of around 4,4 million people each year, almost 8% of all deaths [@World_Health_Organization_2021]. In the United States, trauma is the 4th leading cause of death among the general population and the leading cause for people between the ages of 1 and 44 [@AAST_2020]. It is also an important cause of hospitalization and morbidity among all age groups, including seniors, and is responsible for an estimated 10% of all years lived with a disability globally. This has a significant burden on social and economic level, costing countries billions of US dollars each year in healthcare and lost productivity[@connolly_woo_lampron_perry_2018]. Studies estimate the cost of trauma care being between 18,500\$ and 41,500\$ in HIC<!-- Spell out the first time you mention HIC-->, depending on the country [@Willenberg_Curtis_Taylor_Jan_Glass_Myburgh_2012]. However, as one might expect<!-- Phrases like "as one might expect", "it is known that", "as has been shown" are usually unecessary and don't add much. Only use them if you need the extra words -->, this burden is not evenly distributed between or within countries. Many social factors such as age, sex and social status play a major role in the risk of dying from trauma, with young men with low socio-economic status being at most risk [@World_Health_Organization_2021]. It is not only patient level factors that affect how people might be affected<!-- affect and affect--> by trauma. About 90% of all trauma related deaths occur in low- and middle-income countries (LMIC), with death rates by trauma also being higher than in high income countries. Even within these LMIC, people of poorer socio-economic status have higher death rates from trauma. Problems identified within these countries that contribute to these statisitics were infrastructure, education and training, attributed to lack of funding, brain drain to HIC and lack of availability of basic amenities [@Shanthakumar_Payne_Leitch_Alfa-Wali_2021]. In HIC where funding and governance over the healthcare system is better designed, functioning trauma systems and dedicated trauma centers exist that have been shown to lower mortality but also improve functional outcome in trauma patients [@Nirula_Brasel_2006].

**Trauma systems**

Trauma systems are infrastructures that exist to provide and optimize care for injured patients starting with injury recognition and triage, transport to appropriate trauma center, inpatient care and outpatient follow-up. Beyond the clinical side, it<!-- DO you mean trauma systems?--> works with outreach, education and advocacy, data collection through registries, research, funding, and disaster preparedness and response. A comprehensive and functioning trauma system requires strong leadership and engagement at the trauma center, regional and national level [@connolly_woo_lampron_perry_2018]. This system is crucial to provide care for trauma patients, both in reducing morbidity and mortality in this patient group. Earlier studies from Sweden have shown that treating severely injured patients at one of these establishments<!-- Trauma center?--> is associated with a 41% lower adjusted 30-day mortality rate compared to being treated at a non trauma care center due to them being more capable of treating these patients, with patients with higher ISS scores having an even higher protective effect with \>90% <!--90% what?-->for the most critically injured patients [@Candefjord_Asker_Caragounis_2020]. Other studies have shown similar results, showing that treating injured patients at trauma centers is associated with a 15-30% decrease in mortality [@Moran_Lecky_Bouamra_Lawrence_Edwards_Woodford_Willett_Coats_2018][@Celso_Tepas_Langland-Orban_Pracht_Papa_Lottenberg_Flint_2006][@MacKenzie_Rivara_Jurkovich_Nathens_Frey_Egleston_Salkever_Scharfstein_2006][@Haas_Stukel_Gomez_Zagorski_De_Mestral_Sharma_Rubenfeld_Nathens_2012]. During the last three decades, the introduction of trauma systems has contributed to lowering the incidence of preventable death . This is attributed to the improvements in care for acute brain injuries and bleeding control. The incidence of late death because of sepsis and multiple organ failure, possibly a result of better and earlier resuscitation [@Asensio_Trunkey_2008]. Functioning trauma systems saves lives in the hospital, but their work outside of the hospital is just as important. Data collection from injured patients, such as mechanism of injury or mortality, are essential for creating databases that can be used for research. In turn, that research can be used for planning injury prevention programs that target the most common injuries in the right ways, e.g. teen drivers, children, specific occupations etc. These injury prevention programs can be planned on trauma center, organizational or government level[@ACS].

Trauma teams are multidisciplinary and operate in these centers. They play a pivotal role in the initial care of the trauma patient, as they are primary care givers in the critical stage of trauma<!-- primary care givers feels a bit odd in this context. PRovide the initial care perhaps?-->. In Sweden, they<!-- Trauma teams?--> include individuals<!-- practitioners?--> from the specialities of surgery, intensive care, orthopedics, nursing and support staff and are lead by a team leader<!-- who is a surgeon-->. Their<!-- The trauma team's?--> aim is to rapidly assess and stabilise the patient, prioritise their injuries and arrange for site of definitive care. Emergency nurses are often the personnel activating the trauma code<!-- Introduce the concept of a trauma code first--> using anatomical and physiological criteria, mechanism of injury and information obtained from emergency service personnel. Once in the trauma room, the team works systematically to assess and manage critically ill patients<!-- Repetition-->. They handle the most urgent problems first, such as airways and breathing, and then tend to less life threatening injuries before readying the patient for transport to the next site of care<!-- What do you mean by "next site of care"?--> [@Hedberg_Falkén_Wihlke_Jansson_Hultgren_Eriksson_Beckman_Haupt_Kjörholt_Sandersjöö_et_al._2020].

**Delay in treatment**

Many hospitals, mainly in HIC, have a registry database<!-- Do you mean trauma registry?--> where they log the patients information and timeline of what happened. This is important work, as a cornerstone of trauma quality improvement programs is multidisciplinary mortality and morbidity review to identify OFIs<!-- You have not mentioned OFI before this. Introduce the concept of OFI above--> and implement corrective actions. This refers to a meeting where different specialities who work with trauma care sit down and go through cases where possible OFIs were identified by nurses who go through the trauma care quality database. These MoM conferences are very resource and time craving, which is why many hospitals doesn't<!-- Do not use contractions--> have the means to perform them. In Sweden<!-- Something is missing here-->

<!-- I suggest that you introduce the concept of trauma qulity improvement programmes, including mortality and morbidity review and OFI, before you introduce delay in treatment--> 

Examples of opportunities for improvement may include lack of resources and management errors. One common OFI that this paper will look further into is delayed treatment. Among the preventable or possibly preventable deaths in trauma patients, a subgroup of patients determined by the Combined Trauma Death Review Committee<!-- What's this? Elaborate-->, delay in treatment has been identified as a major error contributing to death, found in up to 52.9% of patients in said group [@Teixeira_Inaba_Hadjizacharia_Brown_Salim_Rhee_Browder_Noguchi_Demetriades_2007]. Although it is such a common OFI, the patient level factors associated with delayed treatment are poorly understood. There may be several factors that correlate with receiving delayed treatment, but they have yet to be identified. Mapping these factors may help in identifying patients that might be at risk for receiving delayed treatment before it happens.<!-- Elaborate on the potential risks of delayed treatment and give examples-->

The aim of this paper is to determine what different patient level factors affect the risk of receiving delayed treatment at a trauma center.

# Methods

**Study design**

This is a registry based cohort study using data from the trauma registry and trauma care quality database at the Karolinska University Hospital in Solna. The trauma registry includes about 14000 patients treated between 2012 and 2022. The trauma care quality database is a subset of the trauma registry and includes about 8000 patients selected for review between 2013 and 2022. The outcome is delayed treatment<!-- You can have a separate heading called Outcome-->, as identified by the multidisciplinary review board and recorded in the trauma care quality database. This project will link the two databases and assess how different patient level factors, such as age, sex, mechanism of injury, and injury severity, are associated with delayed treatment using logistic regression. A 5% significance level and 95% confidence levels will be used.<!-- This last line should be under statistical methods-->

**Setting**

Every year, Karolinska University hospital, which is the equivalent of a trauma level 1 hospital, admits 1500 trauma patients each year to their facility<!-- Last part is repetition-->. To be added to the trauma registry, a patient must be over 15 years of age, had ISS\>9 and/or had trauma code activation. They get added to both the Karolinska Trauma registry but also the national trauma registry (SweTrau). The trauma registry includes data on vital signs, injuries, interventions and patient information. A subset to this database, the trauma care quality database<!-- Use more direct language: The trauma care quality database is a subset...--> includes information relevant for mortality and morbidity conferences

**Participants**

The database only includes patients 15 and above, ISS \>9 and/or trauma team activation. Inclusion in the study further requires that the patients have been assessed for OFIs. Exclusion happens<!-- Same here, use direct language: Patients were excluded if...--> if a patient is missing information in one of the examined patient factors.

**Variables**

The outcome is delayed treatment, which is defined as more than 30 minutes passing from arrival before receiving treatment, as identified by the multidisciplinary review board and recorded in the trauma care quality database. This project will link the two databases and assess how different patient level factors, such as age, sex, mechanism of injury, and injury severity, are associated with delayed treatment using logistic regression. A 5% significance level and 95% confidence levels will be used.<!-- Did you forget to remove these two last sentence?-->

**Data sources/measurement**

The data comes from the trauma registry and trauma care quality database.

**Bias**

Bias is not relevant in this study as the data is collected from a database and processed by a coding program.<!-- Not quite true, there are multiple biases that may come into play, for example selection bias, i.e. is the sample representative of the population to which you want to generalise?-->

**Study size**

The study size is all of the eligible patients that was treated at the hospital between 2012 and 2022. Starting 2013 only a subgroup of patients were screened for OFIs, but starting 2017 all patients that are included in the database are screened for OFIs.

**Quantitative variables**

**Statistical methods**
